apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal-tracker-backend
  # namespace will be set via kubectl -n flag
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: goal-tracker-backend
  template:
    metadata:
      labels:
        app: goal-tracker-backend
    spec:
      containers:
      - name: backend
        image: us-docker.pkg.dev/PROJECT_ID/gcr.io/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: goal-tracker-backend-service
  # namespace will be set via kubectl -n flag
spec:
  selector:
    app: goal-tracker-backend
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
