apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal-tracker-frontend
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goal-tracker-frontend
  template:
    metadata:
      labels:
        app: goal-tracker-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/goal-tracker-frontend:staging-SHA
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: staging
spec:
  selector:
    app: goal-tracker-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
