apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal-tracker-backend
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goal-tracker-backend
  template:
    metadata:
      labels:
        app: goal-tracker-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/PROJECT_ID/goal-tracker-backend:main-SHA
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://production-db:3306/goaltracker"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/goals/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/goals/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
spec:
  selector:
    app: goal-tracker-backend
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
