apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: goal-tracker-ksa
      containers:
      - name: goal-tracker-frontend-sha256-1
        image: gcr.io/rosy-slate-468308-r5/goal-tracker-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
